name: Website Deployment
on: 
  workflow_call:
     inputs:
        artifact-name:
           description: the name of input
           required: false
           default: testing
           type: string
jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: reuse test
        run: echo ${{inputs.artifact-name}}