name: Website Deployment
on: 
  workflow_call:
     inputs:
        artifact-name:
           description: the name of input
           required: false
           default: testing
           type: string
    secrets:
       some-secret:
           required: false 
    outputs:
         result:
            value: ${{jobs.reuse.outputs.stepresult}}             
jobs:
  outputs:
      outcome:${{steps.result.outputs.stepresult}}
  reuse:
    runs-on: ubuntu-latest
    steps:
      - name: reuse test
        id: reult
        run: |
         echo ${{inputs.artifact-name}}
         echo "::set-output name=stepresult::success"